version: '3'

services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gallery-webserver
    container_name: gallery-webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=10000

  #volumes:
    #swima-data:
    #vendor:
  #assets:


